# Generated by Django 4.0.4 on 2022-04-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearpost',
            name='cuerpo',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='crearpost',
            name='fecha_creacion',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='crearpost',
            name='imagen',
            field=models.CharField(max_length=40),
        ),
    ]
