# Generated by Django 4.0.4 on 2022-04-16 23:18

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_crearpost_cuerpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crearpost',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='crearpost',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='crearpost',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blogimagen'),
        ),
    ]
