# Generated by Django 4.0.4 on 2022-04-16 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_crearpost_cuerpo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crearpost',
            name='fecha_creacion',
        ),
    ]
