# Generated by Django 4.0.4 on 2022-04-16 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_remove_crearpost_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearpost',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
