# Generated by Django 4.0.4 on 2022-04-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_crearpost_fecha_creacion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CrearPost',
            new_name='Post',
        ),
    ]
